###
GET http://localhost:4000/employess

###
POST http://localhost:4000/employess
Content-Type: application/json

{
    "name": "7R0N1X",
    "position": "Snr. Developer",
    "office": "Rome",
    "salary": "23000"
}

###
GET http://localhost:4000/employess/62af3e1ddcca45880c05a51b

###
DELETE http://localhost:4000/employess/62af469a411ab37da2a41594

###
PUT http://localhost:4000/employess/62af3e1ddcca45880c05a51b
Content-Type: application/json

{
    "salary": 90000
}